# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Cached
version:      1.33
version_from: lib/WWW/Mechanize/Cached.pm
installdirs:  site
requires:
    Cache::Cache:                   1.02
    Carp:                           0
    Storable:                       2.08
    Test::More:                     0.47
    Test::Warn                      0.11
    WWW::Mechanize:                 1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21_03
